### ISSUE TITLE
validator dependencies

### ISSUE THREAD

**Issue by 7wonders** [adamwaite/Validator#15]
Really nice library :)

It would be great to be able to set a priority of dependencies. At the moment if setting the required and min length validator for example, it will return errors for both. It would be nice if you could set that it will only validate min length if required is already validated. This becomes especially useful with remote validation i.e. don't bother hammering the server if the instance is not at least 5 chars. Make sense or is there a way of doing similar already that I totally missed (without doing a bunch of unique validators stuck inside an if isvalid condition)?

**Comment by adamwaite** [comment]
Hey. Thanks for the suggestion. Actually that makes much more sense, I should have built that in. Unfortunately I'm no longer maintaining the Objective-C implementation because I use Swift at work and at home now, but please feel free to make a pull request on the objc branch. Otherwise, perhaps create 2 validator objects (one for remote) only calling the second once the first completes.
